// ignore_for_file: constant_identifier_names

class SharedPrefKeys {
  static const USERSETTING_PARENT_KEY = 'USERSETTING_PARENT_KEY';
  static const USERSETTING_GENERATED_KEY = 'USERSETTING_GENERATED_KEY';
  static const USERSETTING_CUSTOMERGROUP_KEY = 'PAYMETHODS_PARENT_KEY';
  static const USERSTORE_PARENT_KEY = 'USERSTORE_PARENT_KEY';
  static const USERID_KEY = 'USERID_KEY';
  static const TOKEN_KEY = 'TOKEN_KEY';
  static const REFRESHTOKEN_KEY = 'REFRESHTOKEN_KEY';
  static const BRANCHID_KEY = 'BRANCHID_KEY';

  static const AUTH_KEY = 'AUTH_KEY';
  static const USERINFO_KEY = 'USERINFO_KEY';

  static const BRANCHINFO_KEY = 'BRANCHINFO_KEY';
  static const COMPANY_KEY = 'COMPANY_KEY';
  static const CURENCIES_KEY = 'CURENCIES_KEY';
  static const SYSTEMDOCS_KEY = 'SYSTEMDOCS_KEY';
  static const USERSETTING_KEY = 'USERSETTING_KEY';
  static const PAYMETHODS_KEY = 'PAYMETHODS_KEY';
  static const USERSTORE_KEY = 'USERSTORE_KEY';
  static const UNITS_KEY = 'UNITS_KEY';
  static const ITEMGROUP_KEY = 'ITEMGROUP_KEY';
  static const ITEMS_KEY = 'ITEMS_KEY';
  static const ITEMUNITS_KEY = 'ITEMUNITS_KEY';
  static const ITEMALTER_KEY = 'ITEMALTER_KEY';
  static const ITEMBARCODE_KEY = 'ITEMBARCODE';
  static const ACCOUNTS_KEY = 'ACOUNTS_KEY';
  static const REF_ACCOUNTS_KEY = 'REF_ACCOUNTS_KEY';
  static const MID_ACCOUNTS_KEY = 'MID_ACOUNTS_KEY';
  static const ACCOUNTOPERAION_KEY = 'ACCOUNTOPERAION_KEY';
  static const STOREOPERATION_KEY = 'STOREOPERATION_KEY';

  static const DATETIME_AUTH_KEY = 'DATETIME_AUTH_KEY';
  static const DATETIME_USERINFO_KEY = 'DATETIME_USERINFO_KEY';
  static const DATETIME_USERID_KEY = 'DATETIME_USERID_KEY';
  static const DATETIME_BRANCHINFO_KEY = 'DATETIME_BRANCHINFO_KEY';
  static const DATETIME_COMPANY_KEY = 'DATETIME_COMPANY_KEY';
  static const DATETIME_CURENCIES_KEY = 'DATETIME_CURENCIES_KEY';
  static const DATETIME_SYSTEMDOCS_KEY = 'DATETIME_SYSTEMDOCS_KEY';
  static const DATETIME_USERSETTING_KEY = 'DATETIME_USERSETTING_KEY';
  static const DATETIME_PAYMETHODS_KEY = 'DATETIME_PAYMETHODS_KEY';
  static const DATETIME_USERSTORE_KEY = 'DATETIME_USERSTORE_KEY';
  static const DATETIME_UNITS_KEY = 'DATETIME_UNITS_KEY';
  static const DATETIME_ITEMGROUP_KEY = 'DATETIME_ITEMGROUP_KEY';
  static const DATETIME_ITEMS_KEY = 'DATETIME_ITEMS_KEY';
  static const DATETIME_ITEMUNITS_KEY = 'DATETIME_ITEMUNITS_KEY';
  static const DATETIME_ITEMALTER_KEY = 'DATETIME_ITEMALTER_KEY';
  static const DATETIME_ITEMBARCODE_KEY = 'DATETIME_ITEMBARCODE_KEY';
  static const DATETIME_REF_ACCOUNTS_KEY = 'DATETIME_REF_ACCOUNTS_KEY';
  static const DATETIME_ACCOUNTS_KEY = 'DATETIME_ACCOUNTS_KEY';
  static const DATETIME_MID_ACCOUNTS_KEY = 'DATETIME_MID_ACCOUNTS_KEY';
  static const DATETIME_ACCOUNTOPERAION_KEY = 'DATETIME_ACCOUNTOPERAION_KEY';
  static const DATETIME_STOREOPERATION_KEY = 'DATETIME_STOREOPERATION_KEY';
}
