// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTRM4jrUq6N53Xgyo2IoKCgc9MU-qwPbM',
    appId: '1:667706006758:web:2e8d7be6eff254b3636f27',
    messagingSenderId: '667706006758',
    projectId: 'new-art-34bdd',
    authDomain: 'new-art-34bdd.firebaseapp.com',
    storageBucket: 'new-art-34bdd.firebasestorage.app',
    measurementId: 'G-869LHXSLZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCua-RnEy5YbBXVq-h5WOnIe2znBYphX9A',
    appId: '1:667706006758:android:f3699989c0aa71d1636f27',
    messagingSenderId: '667706006758',
    projectId: 'new-art-34bdd',
    storageBucket: 'new-art-34bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPtIIEcNEmcTjivdH8UQ9jjKJDUWk17M',
    appId: '1:667706006758:ios:26cd9f3a6695e4f3636f27',
    messagingSenderId: '667706006758',
    projectId: 'new-art-34bdd',
    storageBucket: 'new-art-34bdd.firebasestorage.app',
    androidClientId: '667706006758-4ossppsocgtm79l3igo1timv23d9nvrg.apps.googleusercontent.com',
    iosClientId: '667706006758-jdonaolhjfk8eom7ieagh8nf1krlu488.apps.googleusercontent.com',
    iosBundleId: 'com.example.newart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPtIIEcNEmcTjivdH8UQ9jjKJDUWk17M',
    appId: '1:667706006758:ios:26cd9f3a6695e4f3636f27',
    messagingSenderId: '667706006758',
    projectId: 'new-art-34bdd',
    storageBucket: 'new-art-34bdd.firebasestorage.app',
    androidClientId: '667706006758-4ossppsocgtm79l3igo1timv23d9nvrg.apps.googleusercontent.com',
    iosClientId: '667706006758-jdonaolhjfk8eom7ieagh8nf1krlu488.apps.googleusercontent.com',
    iosBundleId: 'com.example.newart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTRM4jrUq6N53Xgyo2IoKCgc9MU-qwPbM',
    appId: '1:667706006758:web:40829306da58c135636f27',
    messagingSenderId: '667706006758',
    projectId: 'new-art-34bdd',
    authDomain: 'new-art-34bdd.firebaseapp.com',
    storageBucket: 'new-art-34bdd.firebasestorage.app',
    measurementId: 'G-8DSJ6EJT5H',
  );

}