platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase Pods (all from local path)
  pod 'FirebaseCore', :git => 'git@github.com:firebase/firebase-ios-sdk.git', :branch => 'CocoaPods-10.25.0'
  pod 'FirebaseAuth', :git => 'git@github.com:firebase/firebase-ios-sdk.git', :branch => 'CocoaPods-10.25.0'
  pod 'FirebaseCoreInternal', :git => 'git@github.com:firebase/firebase-ios-sdk.git', :branch => 'CocoaPods-10.29.0'  
  pod 'Firebase/Analytics', :path => './firebase-ios-sdk'
  pod 'FirebaseAppCheckInterop', :git => 'git@github.com:firebase/firebase-ios-sdk.git', :branch => 'CocoaPods-10.29.0'
  pod 'FirebaseInstallations', :git => 'git@github.com:firebase/firebase-ios-sdk.git', :branch => 'CocoaPods-10.29.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end